export enum ApiRoutes {
  HEALTH_CHECK = "health-check",
  GET_CONVEYORS = "conveyors",
  GET_RONDEL_TYPES = "rondel-types",
  GET_EMPLOYEES_BY_BARCODE = "employees/by_barcode",
  GET_LABORATORY_ASSISTANT_BY_BARCODE = "laboratory-assistants/by_barcode",
  GET_SUMMARY_RAW_MATERIALS_BY_SUMMARY_ID = "summary-raw-materials/by_summary_id",
  GET_ACTIVE_SUMMARY = "summaries/active",
  GET_ACTIVE_SUMMARY_NEW = "summaries",

  GET_ACTIVE_SUMMARY_COUNTERS = "summaries/active_counters",
  GET_SUMMARY_RAW_MATERIALS_CURRENT = "summary-raw-material-current/get_list",
  GET_CHIEF_TECHNOLOGIST_NOTE = "chief-technologist-notes/by_summary_id",
  GET_EXTRUSION_HARDWARE_TRESHOLDS = "extrusion/hardware/get_trehsholds",
  GET_EXTRUSION_HARDWARE_CURRENT_PARAMS = "extrusion/hardware/get_params",
  GET_EXTRUSION_HARDWARE_ALL_PARAMS = "extrusion/hardware/get_all_params",
  CREATE_EXTRUSION_HARDWARE_CURRENT_PARAM = "extrusion/hardware/create_params_record",
  CREATE_SUMMARY_RAW_MATERIALS_CURRENT = "summary-raw-material-current/create",
  GET_EXTRUSION_QUALITY_TRESHOLDS = "extrusion/quality_control/get_trehsholds",
  GET_EXTRUSION_QUALITY_CURRENT_PARAMS = "extrusion/quality_control/get_params",
  GET_EXTRUSION_QUALITY_ALL_PARAMS = "extrusion/quality_control/get_all_params",
  CREATE_EXTRUSION_QUALITY_CURRENT_PARAM = "extrusion/quality_control/create_params_record",

  CREATE_EXTRUSION_ENTRY = "/extrusion/params",
}
