FROM node:18

WORKDIR /app

COPY ./app/package*.json ./
COPY ./app/tsconfig*.json ./
COPY ./app/vite.config*.json ./

COPY ./app/src ./src

RUN npm install

COPY ./app .


# RUN npm run build


CMD ["npm", "run", "dev"]

# EXPOSE 3000