FROM node:18-alpine

WORKDIR /app

COPY ./app/package*.json ./
COPY ./app/tsconfig*.json ./
COPY ./app/vite.config*.json ./
COPY ./app/src ./src
RUN npm install
COPY ./app .
RUN npm run build
RUN npm i -g http-server
CMD ["http-server", "-p3000", "./dist"]
