services:
  nginx:
    container_name: nginx_container
    build: ./docker/nginx
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
      - "5000:5000"
    networks:
      - general

  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: "summary"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    volumes:
      - summary-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "eagle221174@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: docker/api/Dockerfile.dev
      args:
        - NODE_ENV=development
    environment:
      POSTGRESHOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "summary"
      PORT: "7000"
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres
      - general

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: docker/app/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    networks:
      - general

  workstation:
    container_name: ws_container
    build:
      context: .
      dockerfile: docker/workstation/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    networks:
      - general

  dashboard:
    container_name: dash_container
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    networks:
      - general

volumes:
  summary-data:
  pgadmin-data:
networks:
  general:
    driver: bridge
  postgres:
    driver: bridge
