services:
  postgres:
    container_name: postgres_container
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: "summary"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      MSSQL_HOST: ${MSSQL_HOST}
      MSSQL_USERNAME: ${MSSQL_USERNAME}
      MSSQL_PASSWORD: ${MSSQL_PASSWORD}
      MSSQL_DB: ${MSSQL_DB}
    volumes:
      - summary-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "eagle221174@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres
    depends_on:
      - postgres

  api:
    container_name: api_container
    build:
      context: .
      dockerfile: docker/api/Dockerfile.prod
      args:
        - NODE_ENV=production
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "summary"
      PORT: "7000"
      BOT_TOKEN: ${BOT_TOKEN}
      CHAT_ID: ${CHAT_ID}
    depends_on:
      - postgres
    restart: always
    networks:
      - postgres
      - general

  app:
    container_name: app_container
    build:
      context: .
      dockerfile: docker/application/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    restart: always
    networks:
      - general

  workstation:
    container_name: ws_container
    build:
      context: .
      dockerfile: docker/workstation/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    restart: always
    networks:
      - general

  dash:
    container_name: dash_container
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile.prod
      args:
        - NODE_ENV=production
    depends_on:
      - api
    restart: always
    networks:
      - general

  nginx:
    container_name: nginx_container
    build: ./docker/nginx
    restart: always
    ports:
      - "80:80"
      - "3000:3000"
      - "5000:5000"
    networks:
      - general
    depends_on:
      - app
      - workstation

volumes:
  summary-data:
  pgadmin-data:
networks:
  general:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
