FROM node:18-alpine

WORKDIR /tubes_application

COPY ./tubes_application/package*.json ./
COPY ./tubes_application/tsconfig*.json ./
COPY ./tubes_application/vite.config*.json ./
COPY ./tubes_applicationh/src ./src
RUN npm ci
COPY ./tubes_application .
RUN npm run build
RUN npm i -g http-server
CMD ["http-server", "-p3000", "./dist"]
