export enum RouteNames {
  HOME = "/",
  LOGIN = "/login",
  FORBIDDEN = "/forbidden",
  SUMMARY_UPLOAD = "/summary_upload",
  SUMMARY_LIST = "/summary_list",
  SUMMARY_DETAIL = "/summary/:summary_id",
  RECORD_DETAIL = "/record/:record_id",
  LABORATORY = "/laboratory",

  // REPORTS = "/reports",
  ADMIN = "/admin",
  // FORBIDDEN = "/forbidden",
  // USERS = "/admin/users",
  TECHNOLOGIST = "/technologist",
  // PLANNER = "/planner",

  // REPORT1 = "/reports/1",
  EMPLOYERS = "/employers",
  BOILS_LIST = "/boils_list",
  BOILS_REPORT = "/boils_report",
  SUMMARY_REPORT = "/summary_report",
  FOREMAN = "/foreman",
  USERS_LIST = "/users_list",
}
