import Doc from "src/docs/docs.model";
import { DocsService } from "src/docs/docs.service";
import { HistoriesService } from "src/histories/histories.service";
import Record from "src/records/records.model";
import { RecordsService } from "src/records/records.service";
import { GetCurrentDocDto } from "./dto/get-current-doc.dto";
import { GetDocByIdDto } from "./dto/get-doc-by-id.dto";
import { SemiProductsService } from "src/semi_products/semi_products.service";
import { RecordRegulationsService } from "src/record_regulations/record_regulations.service";
import { TimeReportDto } from "./dto/time-report.dto";
import { RecordCountersService } from "src/record_counters/record_counters.service";
export declare class DocDetailService {
    private docsService;
    private recordsService;
    private historiesService;
    private semiProductsService;
    private recordRegulationsService;
    private recordsCountersService;
    constructor(docsService: DocsService, recordsService: RecordsService, historiesService: HistoriesService, semiProductsService: SemiProductsService, recordRegulationsService: RecordRegulationsService, recordsCountersService: RecordCountersService);
    recordResult<Type extends {
        id: number;
        productId: string;
        product: string;
        boil: string;
        plan: number;
        fact: number;
        apparatus: string;
        bbf: string;
        note: string;
        can: string;
        conveyor: string;
        workshop: string;
        historiesCount: number;
        state: string;
        stateValue: string;
        isSet: boolean;
    }>(item: Record): Promise<{
        id: any;
        productId: any;
        product: any;
        boil: any;
        plan: any;
        fact: any;
        apparatus: any;
        bbf: any;
        dm: any;
        note: any;
        can: any;
        conveyor: any;
        workshop: any;
        historiesCount: any;
        state: any;
        stateValue: any;
        stateTime: any;
        isUpdated: boolean;
        isSet: any;
        semiProducts: any;
        regulation: any;
        water_base_id: any;
        plant_id: any;
        history_note: any;
    }>;
    getDocDetailData(doc: Doc): Promise<any>;
    getAppDocDetailData(doc: Doc): Promise<any>;
    getDocDetailDataWithFilter(doc: Doc, dto: GetCurrentDocDto): Promise<any>;
    getDocRowDetailData(recordId: number): Promise<{
        id: any;
        productId: any;
        product: any;
        boil: any;
        plan: any;
        fact: any;
        apparatus: any;
        bbf: any;
        dm: any;
        note: any;
        can: any;
        conveyor: any;
        workshop: any;
        historiesCount: any;
        state: any;
        stateValue: any;
        stateTime: any;
        isUpdated: boolean;
        isSet: any;
        semiProducts: any;
        regulation: any;
        water_base_id: any;
        plant_id: any;
        history_note: any;
    }>;
    getCurrentDocDetail(plantId: number): Promise<any>;
    getTomorrowAppDocDetail(plantId: number): Promise<any>;
    getCurrentAppDocDetail(plantId: number): Promise<any>;
    getDocDetailByDocId(docId: number): Promise<any>;
    getCurrentDocDetailWithFilter(dto: GetCurrentDocDto): Promise<any>;
    getDocDetailByIdWithFilter(dto: GetDocByIdDto): Promise<any>;
    getTimeReport(dto: TimeReportDto): Promise<any>;
    timeResult(item: Record): Promise<{
        id: any;
        state: any;
        stateValue: any;
        conveyor: any;
        productId: any;
        product: any;
        boil: any;
        plan: any;
        lastBaseCheck: any;
        lastPlugPass: any;
        lastProductCheck: any;
        lastProductPass: any;
        lastProductInProgress: any;
        lastProductFinished: any;
    }>;
}
