FROM node:18

WORKDIR /api_tubes
COPY ./api_tubes/package*.json ./
COPY ./api_tubes/tsconfig*.json ./
COPY ./api_tubes/src ./src
RUN npm install
COPY ./api_tubes .
RUN npx prisma generate
RUN npm run build
RUN npx prisma migrate deploy
RUN npx prisma migrate status

CMD ["npm", "run", "start:prod"]