FROM node:18-alpine

WORKDIR /dashboard

COPY ./dashboard/package*.json ./
COPY ./dashboard/tsconfig*.json ./
COPY ./dashboard/vite.config*.json ./
COPY ./dashboard/src ./src
RUN npm install
COPY ./dashboard .
RUN npm run build
RUN npm i -g http-server
CMD ["http-server", "-p3000", "./dist"]
