export const PG_USER_ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  PLANNER: 'PLANNER',
  LABORATORY: 'LABORATORY',
  TECHNOLOGIST: 'TECHNOLOGIST',
  FOREMAN: 'FOREMAN',
  EMPLOYERS: 'EMPLOYERS',
  GODMODE: 'GODMODE',
  REPORTS: 'REPORTS',
  CARDS: 'CARDS',
  WEIGHER: 'WEIGHER',
  TRACE: 'TRACE',
  WGHT_GODMODE: 'WGHT_GODMODE',
} as const;

export type TPGUserRole = (typeof PG_USER_ROLES)[keyof typeof PG_USER_ROLES];
