export const ROUTE_PATH = {
  DASH: '/',
  LOGIN: '/login',
  FORBIDDEN: '/forbidden',
  PLANNER: '/planner',
  PLANNER_SUMMARIES: '/planner/docs',
  PLANNER_SUMMARY_DETAIL: (docId: string | number) => `/planner/docs/${docId}` as const,
  PLANNER_CONVEYORS: '/planner/conveyors',
  LAB: '/laboratory',
  LAB_BOILS: '/laboratory/boils',
  LAB_PRODUCTS: '/laboratory/products',
  TECH: '/technologist',
  TECH_CANS_DASH: '/technologist/cans_dash',
  TECH_CANS_LIST: '/technologist/cans_list',
  TECH_CANS_LOCATION: '/technologist/cans_location',
  WEIGHT_SECTION: '/weight_section',
  WEIGHT_SECTION_INVENTORIES: '/weight_section/inventories',
  WEIGHT_SECTION_WEIGHT_REPORTS: '/weight_section/weight_reports',
  WEIGHT_SECTION_PRODUCTIVITY: '/weight_section/productivity',
  WEIGHT_SECTION_BOILS_UPLOAD: '/weight_section/boils_upload',
  FOREMAN: '/foreman',
  REPORTS: '/reports',
  REPORTS_TIMING: '/reports/timing',
  REPORTS_BOILS: '/reports/boils',
  EMPLOYEES: '/employees',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
} as const;
