export enum RouteNames {
  NOT_FOUND = "*",
  EXTRUSION_ROOT = "/extrusion",
  EXTRUSION = "/extrusion/:conveyor_name",
  EXTRUSION_ADD_ENTRY_ROOT = "/extrusion_add_entry",
  EXTRUSION_ADD_ENTRY = "/extrusion_add_entry/:conveyor_name",
  VARNISH_ROOT = "/varnish",
  VARNISH = "/varnish/:conveyor_name",
  VARNISH_ADD_ENTRY_ROOT = "/varnish_add_entry",
  VARNISH_ADD_ENTRY = "/varnish_add_entry/:conveyor_name",
  OFFSET_ROOT = "/offset",
  OFFSET = "/offset/:conveyor_name",
  OFFSET_ADD_ENTRY_ROOT = "/offset_add_entry",
  OFFSET_ADD_ENTRY = "/offset_add_entry/:conveyor_name",
  SEALANT_ROOT = "/sealant",
  SEALANT = "/sealant/:conveyor_name",
  SEALANT_ADD_ENTRY_ROOT = "/sealant_add_entry",
  SEALANT_ADD_ENTRY = "/sealant_add_entry/:conveyor_name",
  PICTURES = "/pictures/:product_id",
  PICTURES_ROOT = "/pictures",
}
