 # 1. Используем базовый образ Node.js с поддержкой pnpm
FROM node:20-alpine3.20 AS base
RUN npm i -g pnpm

WORKDIR /app

# 2. Копируем корневые файлы конфигурации монорепозитория
COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# 3. Копируем package.json файлы всех необходимых пакетов (для кэширования слоев)
# Это нужно, чтобы pnpm install не перезапускался, если код изменился, но зависимости те же
COPY packages/trpc/package.json ./packages/trpc/
COPY apps/dash/package.json ./apps/dash/

# 4. Устанавливаем зависимости для всего воркспейса
RUN pnpm install --frozen-lockfile

# 5. Копируем исходный код общего пакета типов и собираем его (если требуется сборка)
COPY packages/trpc ./packages/trpc
# RUN pnpm --filter trpc build # Раскомментируйте, если вашему @repo/trpc нужна компиляция в dist

# 6. Копируем исходный код самого фронтенд-приложения
COPY apps/dash ./apps/dash

# 7. Собираем только приложение dash
RUN pnpm --filter dash build

# 8. Устанавливаем легковесный сервер для раздачи статики
RUN npm i -g http-server

EXPOSE 3000

# 9. Запускаем сервер из папки сборки конкретного приложения
# CMD ["http-server", "-p3000", "./apps/dash/dist"]
CMD ["http-server", "-p", "3000", "--proxy", "http://localhost:3000?", "./dist"]
