SELECT 
"Doc"."id", 
"Doc"."plantId", 
"Doc"."date", 
"Doc"."createdAt", 
"Doc"."updatedAt", 
"records"."id" AS "records.id", 
"records"."docId" AS "records.docId", 
"records"."productId" AS "records.productId", 
"records"."boilId" AS "records.boilId", 
"records"."apparatusId" AS "records.apparatusId", 
"records"."canId" AS "records.canId", 
"records"."conveyorId" AS "records.conveyorId", 
"records"."plan" AS "records.plan", 
"records"."bbf" AS "records.bbf", 
"records"."note" AS "records.note", 
"records"."workshopId" AS "records.workshopId", 
"records"."createdAt" AS "records.createdAt", 
"records"."updatedAt" AS "records.updatedAt", 
COUNT("history"."id") AS "records.hists", 
"records->histories"."id" AS "records.histories.id", 
"records->histories"."recordId" AS "records.histories.recordId", 
"records->histories"."historyTypeId" AS "records.histories.historyTypeId", 
"records->histories"."userId" AS "records.histories.userId", "records->histories"."employeeId" AS "records.histories.employeeId", "records->histories"."note" AS "records.histories.note", "records->histories"."createdAt" AS "records.histories.createdAt", "records->histories"."updatedAt" AS "records.histories.updatedAt" FROM "docs" AS "Doc" LEFT OUTER JOIN ( "records" AS 
"records" 
INNER JOIN "histories" AS "records->histories" ON "records"."id" = "records->histories"."recordId" ) ON "Doc"."id" = "records"."docId"