name: Monorepo CI

on:
  push:
    branches: [repo] #[main]
  pull_request:
    branches: [repo] #[main]

jobs:
  pre-flight:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10 
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate All Prisma Clients
        run: pnpm db:generate
      - name: Lint & Type Check All
        run: |
          pnpm monorepo:lint
          pnpm monorepo:typecheck          
      - name: Knip Cleanliness Check
        run: npx knip --reporter github-actions
  build-check:
    needs: pre-flight
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["@repo/api_v2", "@repo/public_api_v2","@repo/application_v2", "@repo/dash", "@repo/workstation"]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma for API v2
        if: matrix.package == '@repo/api_v2'
        run: pnpm db:generate        
      - name: Generate Prisma for Public API
        if: matrix.package == '@repo/public_api_v2'
        run: pnpm --filter @repo/db-postgres generate
      - name: Build ${{ matrix.package }}
        run: pnpm --filter "${{ matrix.package }}" build