export enum DbRoles {
  ADMIN = "Администратор",
  USER = "user",
  SPECIALIST = "specialist",
  LABORATORY = "Лаборант",
  TECHNOLOGIST = "Технолог",
  PLANNER = "Планировщик",
  REPORTS = "Отчеты",
  EMPLOYERS = "Сотрудники",
  TEST = "Тест",
  GODMODE = "Godmode",
  FOREMAN = "Мастер",
  CARDS = "Карточки",
  WEIGHER = "Весовой участок",
}
